---
# ----------------Configure roundcube----------
- name: Copy roundcube vhost
  template:
    src: files/etc/apache2/sites-available/roundcube.vhost.j2
    dest: /etc/apache2/sites-available/roundcube.vhost

- name: Check that roundcube cert is present
  stat:
    path: /etc/letsencrypt/live/{{ roundcube_hostname }}/fullchain.pem
  register: roundcube_stat_result

- name: Enable roundcube vhost
  file:
    src: /etc/apache2/sites-available/roundcube.vhost
    dest: /etc/apache2/sites-enabled/000-roundcube.vhost
    state: link
  when: roundcube_stat_result.stat.exists == true