---
- name: Generate mail password
  set_fact:
      mail_admin_password: "{{ mail.admin_password |
                    default( lookup('password', '/dev/null chars=ascii_letters,digits length=32') ) }}"
- name: Generate phpmyadmin password
  set_fact:
      phpmyadmin_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
  when: phpmyadmin is not defined

- name: Generate roundcube password
  set_fact:
      roundcube_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
  when: roundcube is not defined

- name: Generate ISPConfig passwords
  set_fact:
      ispconfig_admin_password: "{{ ispconfig.ispconfig_admin_password |
                              default( lookup('password', '/dev/null chars=ascii_letters,digits length=32') ) }}"
      ispconfig_mysql_root_password: "{{ ispconfig.mysql_root_password |
                                    default( lookup('password', '/dev/null chars=ascii_letters,digits length=32') ) }}"
      ispconfig_mysql_ispconfig_password: "{{ ispconfig.mysql_ispconfig_password |
                                      default( lookup('password', '/dev/null chars=ascii_letters,digits length=32')) }}"
      ispconfig_mysql_master_root_password: "{{ ispconfig.mysql_master_root_password |
                                    default( lookup('password', '/dev/null chars=ascii_letters,digits length=32') ) }}"

- name: Switch shell to bash
  file:
    src: /bin/bash
    dest: /bin/sh
    state: link

- name: Stop AppArmor
  service:
    name: apparmor
    state: stopped

- name: Remove AppArmor
  apt:
    name: apparmor
    state: absent

- name: Synchronize the system clock (install ntp)
  apt:
    name: ntp
    state: present

- name: Uninstall sendmail
  apt:
    name: sendmail
    state: absent

# ----------------Install packages----------------
- include_tasks: install_packages.yml

# ----------------Configure Postfix----------------
- include_tasks: postfix_configuration.yml

# ----------------Configure Mariadb----------------
- include_tasks: mariadb_configuration.yml

# ----------------Install and configure php and apache----------------
- include_tasks: apache_php_configuration.yml

# ----------------Install and configure pureftp_quota----------------
- include_tasks: amavisd_new_spamassassin_clamav_configuration.yml

# ----------------Install Let's encrypt----------------

- name: Install certbot
  apt:
    name: certbot
    state: present


# ----------------Install and configure mailman----------------
- include_tasks: mailman_configuration.yml

#----------------Install and configure pureftp_quota----------------
- include_tasks: quota_pureftp_configuration.yml

#----------------Install and configure bind dns----------------
- include_tasks: bind_dns_server.yml

#----------------Install and configure bind dns----------------
- include_tasks: install_vlogger_webalizer_awstats.yml

#----------------Install and configure bind dns----------------
- include_tasks: install_jailkit.yml

#----------------Install and configure bind dns----------------
- include_tasks: install_fail2ban_ufw.yml

#----------------Install and configure roundcube----------------
- include_tasks: install_roundcube.yml

#----------------Install and configure ispconfig----------------
- include_tasks: install_ispconfig.yml

- name: Print all passwords
  debug:
    msg:
      - "mail.admin_password: {{ mail.admin_password | default(mail_admin_password) }}"
      - "phpmyadmin.admin_password: {{ phpmyadmin.admin_password if phpmyadmin is defined
                                      else phpmyadmin_admin_password }}"
      - "roundcube.admin_password: {{ roundcube.admin_password if roundcube is defined
                                      else roundcube_admin_password }}"
      - "ispconfig.admin_password: {{ ispconfig.ispconfig_admin_password | default(ispconfig_admin_password) }}"
      - "ispconfig.mysql_root_password: {{ ispconfig.mysql_root_password | default(ispconfig_mysql_root_password) }}"
      - "ispconfig.mysql_ispconfig_password: {{ ispconfig.mysql_ispconfig_password
                                                | default(ispconfig_mysql_ispconfig_password) }}"
      - "ispconfig.mysql_master_root_password: {{ ispconfig.mysql_master_root_password
                                                  | default(ispconfig_mysql_master_root_password) }}"