---
- name: Comment bind-address= 127.0.0.1
  replace:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^(bind-address.*=.*127\.0\.0\.1)$'
    replace: '#\1'

- name: Delete anonymous MySQL server user for {{ ansible_nodename }}
  mysql_user:
    check_implicit_admin: yes
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - ""
    - "localhost"

- name: Remove the MySQL test database
  action: mysql_db login_user=root login_password="{{ ispconfig_mysql_root_password }}" db=test state=absent

- name: Change root user password on first run
  mysql_user:
    check_implicit_admin: yes
    name: root
    password: "{{ ispconfig_mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: "{{ item }}"
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: 'Get pluginstate for mysql user root@localhost'
  shell: |
    mysql -NBe 'SELECT plugin FROM mysql.user WHERE HOST = "localhost" AND USER = "root"'
  failed_when: no
  changed_when: no
  register: mysql_plugin_output

- name: 'Delete plugins from mysql user root@localhost'
  shell: |
    mysql -NBe 'UPDATE mysql.user SET plugin = "" WHERE HOST = "localhost" AND USER = "root"; FLUSH PRIVILEGES;'
  when: mysql_plugin_output.stdout IS NOT ""
